"""
Test data for SQL batch evaluation.
Contains sample evaluation cases with natural queries, expected SQL, and generated SQL.
"""

BATCH_EVALUATIONS = [
    {
        "natural_query": "List of all the blessed seekers in this program?",
        "expected_sql": """SELECT COUNT(*) AS total FROM ( SELECT * FROM ( SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS \"Seeker Name\", COALESCE(u.dob, hr.dob) AS \"Dob\", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS \"Age\", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS \"Gender\", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS \"Location\", COALESCE(u.phone_number, hr.mobile_number) AS \"Mobile Number\", COALESCE(u.email, hr.email_address) AS \"Email\", p.name AS \"Program Name\" FROM hdb_program_registration AS hr LEFT JOIN users AS u ON hr.user_id = u.id LEFT JOIN program_v1 AS p ON hr.allocated_program_id = p.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND NOT hr.allocated_program_id IS NULL ORDER BY \"Seeker Name\" ASC ) AS original_data WHERE NOT \"Seeker Name\" IS NULL AND NOT \"Dob\" IS NULL AND NOT \"Age\" IS NULL AND NOT \"Gender\" IS NULL AND NOT \"Location\" IS NULL AND NOT \"Mobile Number\" IS NULL AND NOT \"Email\" IS NULL AND NOT \"Program Name\" IS NULL ) AS filtered_count""",
        "generated_sql": """SELECT COUNT(*) AS total FROM ( SELECT * FROM ( SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS \"Seeker Name\", COALESCE(u.dob, hr.dob) AS \"Dob\", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS \"Age\", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS \"Gender\", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS \"Location\", COALESCE(u.phone_number, hr.mobile_number) AS \"Mobile Number\", COALESCE(u.email, hr.email_address) AS \"Email\", p.name AS \"Program Name\" FROM hdb_program_registration AS hr LEFT JOIN users AS u ON hr.user_id = u.id LEFT JOIN program_v1 AS p ON hr.allocated_program_id = p.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND NOT hr.allocated_program_id IS NULL ORDER BY \"Seeker Name\" ASC ) AS original_data WHERE NOT \"Seeker Name\" IS NULL AND NOT \"Dob\" IS NULL AND NOT \"Age\" IS NULL AND NOT \"Gender\" IS NULL AND NOT \"Location\" IS NULL AND NOT \"Mobile Number\" IS NULL AND NOT \"Email\" IS NULL AND NOT \"Program Name\" IS NULL ) AS filtered_count""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "List of registered seekers for this program who are female",
        "expected_sql": """SELECT * FROM ( SELECT * FROM ( SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS \"Seeker Name\", COALESCE(u.dob, hr.dob) AS \"Dob\", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS \"Age\", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS \"Gender\", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS \"Location\", COALESCE(u.phone_number, hr.mobile_number) AS \"Mobile Number\", COALESCE(u.email, hr.email_address) AS \"Email\" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND COALESCE(CAST(hr.gender AS VARCHAR), u.gender) ILIKE 'female' AND hr.registration_status <> 'save_as_draft' ORDER BY \"Seeker Name\" ASC ) AS original_data WHERE NOT \"Seeker Name\" IS NULL AND NOT \"Dob\" IS NULL AND NOT \"Age\" IS NULL AND NOT \"Gender\" IS NULL AND NOT \"Location\" IS NULL AND NOT \"Mobile Number\" IS NULL AND NOT \"Email\" IS NULL ) AS filtered_data LIMIT 10 OFFSET 0""",
        "generated_sql": """SELECT * FROM ( SELECT * FROM ( SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS \"Seeker Name\", COALESCE(u.dob, hr.dob) AS \"Dob\", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS \"Age\", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS \"Gender\", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS \"Location\", COALESCE(u.phone_number, hr.mobile_number) AS \"Mobile Number\", COALESCE(u.email, hr.email_address) AS \"Email\" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND COALESCE(CAST(hr.gender AS VARCHAR), u.gender) ILIKE 'female' AND hr.registration_status <> 'save_as_draft' ORDER BY \"Seeker Name\" ASC ) AS original_data WHERE NOT \"Seeker Name\" IS NULL AND NOT \"Dob\" IS NULL AND NOT \"Age\" IS NULL AND NOT \"Gender\" IS NULL AND NOT \"Location\" IS NULL AND NOT \"Mobile Number\" IS NULL AND NOT \"Email\" IS NULL ) AS filtered_data LIMIT 10 OFFSET 0""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "How many seekers got blessed ?",
        "expected_sql": """SELECT COUNT(hr.id) AS "Blessed Seekers Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.allocated_program_id IS NOT NULL AND hr.registration_status <> 'save_as_draft';""",
        "generated_sql": """SELECT COUNT(hr.id) AS "Blessed Seekers Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.allocated_program_id IS NOT NULL AND hr.registration_status <> 'save_as_draft';""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "How many total registrations done for this program ?",
        "expected_sql": """SELECT COUNT(hr.id) AS "Registration Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft';""",
        "generated_sql": """SELECT COUNT(hr.id) AS "Registration Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft';""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "Top 10 cities graph destribution by registered seekers for this program?",
        "expected_sql": """SELECT CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END AS "City", COUNT(hr.id) AS "Registration Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND hr.city IS NOT NULL GROUP BY "City" ORDER BY "Registration Count" DESC LIMIT 10;""",
        "generated_sql": """SELECT CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END AS "City", COUNT(hr.id) AS "Registration Count" FROM hdb_program_registration AS hr WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND hr.city IS NOT NULL GROUP BY "City" ORDER BY "Registration Count" DESC LIMIT 10;""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "Age distribution graph of registered seekers for this program?",
        "expected_sql": """SELECT CASE WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 18 AND 25 THEN '18-25' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 26 AND 35 THEN '26-35' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 36 AND 45 THEN '36-45' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 46 AND 55 THEN '46-55' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 56 AND 65 THEN '56-65' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 THEN '65+' ELSE 'Unknown' END AS "Age Group", COUNT(DISTINCT hr.user_id) AS "Seeker Count" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND COALESCE(u.dob, hr.dob) IS NOT NULL GROUP BY "Age Group" ORDER BY "Age Group";""",
        "generated_sql": """SELECT CASE WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 26 AND 35 THEN '26-35' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 36 AND 45 THEN '36-45' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 46 AND 55 THEN '46-55' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) BETWEEN 56 AND 65 THEN '56-65' WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 THEN '65+' ELSE 'Unknown' END AS "Age Group", COUNT(DISTINCT hr.user_id) AS "Seeker Count" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND COALESCE(u.dob, hr.dob) IS NOT NULL GROUP BY "Age Group" ORDER BY "Age Group";""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "List of registered seekers for this program whose age is above 65",
        "expected_sql": """SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS "Seeker Name", COALESCE(u.dob, hr.dob) AS "Dob", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS "Age", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS "Gender", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS "Location", COALESCE(u.phone_number, hr.mobile_number) AS "Mobile Number", COALESCE(u.email, hr.email_address) AS "Email" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 ORDER BY "Seeker Name" ASC;""",
        "generated_sql": """SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS "Seeker Name", COALESCE(u.dob, hr.dob) AS "Dob", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS "Age", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS "Gender", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS "Location", COALESCE(u.phone_number, hr.mobile_number) AS "Mobile Number", COALESCE(u.email, hr.email_address) AS "Email" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 ORDER BY "Seeker Name" ASC;""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    },
    {
        "natural_query": "List of registered seekers for this program whose age is above 65",
        "expected_sql": """SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS "Seeker Name", COALESCE(u.dob, hr.dob) AS "Dob", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS "Age", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS "Gender", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS "Location", COALESCE(u.phone_number, hr.mobile_number) AS "Mobile Number", COALESCE(u.email, hr.email_address) AS "Email" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 ORDER BY "Seeker Name" ASC;""",
        "generated_sql": """SELECT COALESCE(u.legal_full_name, u.full_name, CASE WHEN NOT u.first_name IS NULL AND NOT u.last_name IS NULL THEN CONCAT(u.first_name, ' ', u.last_name) ELSE COALESCE(u.first_name, u.last_name) END, hr.full_name) AS "Seeker Name", COALESCE(u.dob, hr.dob) AS "Dob", EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) AS "Age", COALESCE(CAST(hr.gender AS VARCHAR), u.gender) AS "Gender", COALESCE(CASE WHEN hr.city = 'Other' THEN hr.other_city_name ELSE hr.city END, CASE WHEN u.address = 'Other' THEN u.other_address ELSE u.address END) AS "Location", COALESCE(u.phone_number, hr.mobile_number) AS "Mobile Number", COALESCE(u.email, hr.email_address) AS "Email" FROM hdb_program_registration AS hr JOIN users AS u ON hr.user_id = u.id WHERE hr.program_id = 38 AND hr.registration_status <> 'save_as_draft' AND EXTRACT(YEAR FROM AGE(CURRENT_DATE, COALESCE(u.dob, hr.dob))) > 65 ORDER BY "Seeker Name" ASC;""",
        "session_id": "batch_demo",
        "metadata": {"model": "gpt-4o-mini", "temperature": 0.7}
    }
]
